[package]
name = "account_proto"
version = "0.1.5"
edition = "2021"
build = "build.rs"
[lib]

[dependencies]
tonic = "0.11.0"
prost = { version = "0.12.3", features = ["prost-derive"] }
prost-types = "0.12.3"
[build-dependencies]
tonic-build = { version = "0.11.0", features = ["prost"] }