[package]
name = "account_proto"
version = "0.1.3"
edition = "2021"
build = "build.rs"
[lib]

[dependencies]
grpc = "0.8.3"
grpc-protobuf = "0.8.3"
protobuf = { version = "~2.18.2", features = ["with-bytes"] }
futures = "~0.3"
bytes = "0.5.*"
tls-api = "0.4.*"
tls-api-native-tls = "0.4.*"
httpbis = "0.9.1"
[build-dependencies]
protoc-rust-grpc = "0.8.3"
